export {
  INITIAL_CATEGORIES,
  INITIAL_COUPONS,
  INITIAL_DELIVERY_CEPS,
  INITIAL_DELIVERY_ZONES,
  INITIAL_PRODUCTION_BATCHES,
  INITIAL_PRODUCTS,
  INITIAL_STORE_SETTINGS,
  SAMPLE_ORDERS,
} from '../data/mockData';
