import {
  Category,
  Coupon,
  DeliveryCepRule,
  DeliveryZone,
  Order,
  ProductionBatch,
  Product,
  StoreSettings,
} from '../types';

export const INITIAL_DELIVERY_CEPS: DeliveryCepRule[] = [
  {
    id: 'cep-1',
    cep: '36830-000',
    label: 'Centro / Espera Feliz',
    fee: 5.0,
    estimated_minutes: 25,
    active: true,
  },
  {
    id: 'cep-2',
    cep: '36830-970',
    label: 'Zona Urbana / Espera Feliz',
    fee: 7.0,
    estimated_minutes: 35,
    active: true,
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-paes',
    name: 'Pães de Fermentação Natural',
    slug: 'paes-fermentacao-natural',
    description: 'Farinha francesa e italiana, 36h de fermentação lenta com nosso levain próprio',
    sort_order: 1,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-folhados',
    name: 'Croissants & Folhados',
    slug: 'croissants-folhados',
    description: 'Manteiga pura de primeira linha, massa folhada crocante e arejada',
    sort_order: 2,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-bolos',
    name: 'Bolos & Doces Artesanais',
    slug: 'bolos-doces',
    description: 'Receitas de família, ingredientes frescos e afeto em cada pedaço',
    sort_order: 3,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-salgados',
    name: 'Salgados & Quiches',
    slug: 'salgados-quiches',
    description: 'Quiches com massa brisée amanteigada e pães de queijo artesanais com queijo canastra curado',
    sort_order: 4,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-cafes',
    name: 'Cafés Especiais & Bebidas',
    slug: 'cafes-bebidas',
    description: 'Grãos 100% arábica de pequenos produtores da Serra do Caparaó',
    sort_order: 5,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat-cestas',
    name: 'Cestas & Presentes',
    slug: 'cestas-presentes',
    description: 'Combinações exclusivas em caixas de madeira artesanal para presentear com carinho',
    sort_order: 6,
    active: true,
    image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-sourdough-tradicional',
    category_id: 'cat-paes',
    name: 'Pão Campagne Tradicional (Levain 36h)',
    slug: 'pao-campagne-tradicional',
    description: 'Pão rústico artesanal de casca crocante e miolo super aerado. Farinha francesa T65, água mineral, sal marinho e nosso levain vivo cultivado há mais de 6 anos.',
    base_price: 25.0,
    promotional_price: null,
    unit: 'unidade (aprox. 650g)',
    is_active: true,
    is_featured: true,
    stock_quantity: 12,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten', 'Pode conter traços de nozes'],
    tags: ['Mais Vendido', 'Vegano', 'Fermentação Lenta'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [2, 3, 4, 5, 6, 0],
      batch_limit: 15,
      days_label: 'Terça a Domingo',
      min_lead_days: 1,
      delivery_window: '08:00 - 12:00',
    },
    options: [
      {
        id: 'opt-corte',
        product_id: 'prod-sourdough-tradicional',
        name: 'Tipo de Corte',
        required: true,
        min_options: 1,
        max_options: 1,
        values: [
          { id: 'corte-inteiro', option_id: 'opt-corte', name: 'Peça Inteira (Preserva o frescor)', price_modifier: 0, is_available: true },
          { id: 'corte-fatiado', option_id: 'opt-corte', name: 'Fatiado em Fatias Médias', price_modifier: 0, is_available: true },
        ],
      },
    ],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-pao-nozes-figo',
    category_id: 'cat-paes',
    name: 'Pão de Nozes com Figos Turcos',
    slug: 'pao-nozes-figo',
    description: 'Pão rústico com blend de farinhas integrais, nozes chilenas tostadas e figos secos macerados.',
    base_price: 34.0,
    promotional_price: null,
    unit: 'unidade (aprox. 550g)',
    is_active: true,
    is_featured: false,
    stock_quantity: 8,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten', 'Nozes'],
    tags: ['Especial', 'Harmoniza com Queijos'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [4, 6],
      batch_limit: 10,
      days_label: 'Quintas e Sábados',
      min_lead_days: 1,
      delivery_window: '08:00 - 12:00',
    },
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-focaccia-alecrim',
    category_id: 'cat-paes',
    name: 'Focaccia Genovese de Alecrim & Flor de Sal',
    slug: 'focaccia-genovese-alecrim',
    description: 'Massa de alta hidratação (85%), azeite de oliva extra virgem importado, ramos frescos de alecrim da nossa horta e flor de sal.',
    base_price: 28.0,
    promotional_price: 24.0,
    unit: 'fatia generosa (aprox. 300g)',
    is_active: true,
    is_featured: true,
    stock_quantity: 15,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten'],
    tags: ['Em Promoção', 'Vegano', 'Receita Italiana'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [3, 5, 6, 0],
      batch_limit: 20,
      days_label: 'Quartas, Sextas, Sábados e Domingos',
      min_lead_days: 1,
      delivery_window: '14:00 - 18:00',
    },
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-baguete-tradicional',
    category_id: 'cat-paes',
    name: 'Baguette Tradicional Francesa',
    slug: 'baguette-tradicional-francesa',
    description: 'Autêntica baguete francesa com pestana bem definida, crocância incomparável e miolo cheio de alvéolos.',
    base_price: 14.0,
    promotional_price: null,
    unit: 'unidade (250g)',
    is_active: true,
    is_featured: false,
    stock_quantity: 20,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten'],
    tags: ['Clássico', 'Fornada Fresca'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [2, 3, 4, 5, 6, 0],
      batch_limit: 25,
      days_label: 'Terça a Domingo',
      min_lead_days: 1,
      delivery_window: '08:00 - 12:00',
    },
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-croissant-manteiga',
    category_id: 'cat-folhados',
    name: 'Croissant Francês de Pura Manteiga',
    slug: 'croissant-frances-manteiga',
    description: 'Folheado clássico feito com manteiga de primeira linha, processo de laminação tradicional em 72 camadas.',
    base_price: 16.0,
    promotional_price: null,
    unit: 'unidade (90g)',
    is_active: true,
    is_featured: true,
    stock_quantity: 18,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten', 'Leite e Derivados', 'Ovos'],
    tags: ['Destaque', 'Café da Manhã'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [2, 3, 4, 5, 6, 0],
      batch_limit: 30,
      days_label: 'Terça a Domingo',
      min_lead_days: 1,
      delivery_window: '08:00 - 12:00',
    },
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-pain-au-chocolat',
    category_id: 'cat-folhados',
    name: 'Pain au Chocolat com Chocolate Belga 54%',
    slug: 'pain-au-chocolat',
    description: 'Massa folhada amanteigada recheada com dois bastões generosos de chocolate belga Callebaut meio amargo.',
    base_price: 18.0,
    promotional_price: null,
    unit: 'unidade (95g)',
    is_active: true,
    is_featured: false,
    stock_quantity: 14,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten', 'Leite', 'Soja', 'Ovos'],
    tags: ['Chocolate Belga', 'Favorito'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [3, 5, 6, 0],
      batch_limit: 20,
      days_label: 'Quartas, Sextas, Sábados e Domingos',
      min_lead_days: 1,
      delivery_window: '08:00 - 12:00',
    },
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-bolo-cenoura-brigadeiro',
    category_id: 'cat-bolos',
    name: 'Bolo Caseiro de Cenoura com Brigadeiro Puxa-Puxa',
    slug: 'bolo-cenoura-brigadeiro',
    description: 'Bolo fofíssimo feito com cenouras frescas e cobertura vulcão generosa de brigadeiro tradicional de colher.',
    base_price: 45.0,
    promotional_price: 39.9,
    unit: 'bolo aro 18 (aprox. 800g)',
    is_active: true,
    is_featured: false,
    stock_quantity: 6,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten', 'Ovos', 'Leite'],
    tags: ['Promoção', 'Sobremesa', 'Conforto'],
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-cesta-cafe-afetivo',
    category_id: 'cat-cestas',
    name: 'Cesta Café Afetivo (Para 2 Pessoas)',
    slug: 'cesta-cafe-afetivo',
    description: 'Caixa rústica de pinus contendo: 1 Pão Campagne, 2 Croissants, 1 Geleia Artesanal de Frutas Vermelhas (200g), 1 Pacote de Café Especial Moído (250g) e 2 Drip Coffees.',
    base_price: 110.0,
    promotional_price: 98.0,
    unit: 'cesta completa',
    is_active: true,
    is_featured: true,
    stock_quantity: 5,
    track_stock: true,
    image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
    allergens: ['Glúten', 'Leite', 'Ovos'],
    tags: ['Presente', 'Mais Vendido', 'Edição Limitada'],
    schedule_config: {
      is_scheduled_only: true,
      available_days: [5, 6, 0],
      batch_limit: 8,
      days_label: 'Sextas, Sábados e Domingos',
      min_lead_days: 1,
      delivery_window: '08:00 - 12:00',
    },
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'AFFETO10',
    description: '10% de desconto na primeira encomenda',
    discount_type: 'PERCENTAGE',
    discount_value: 10,
    min_order_value: 50.0,
    max_discount: 30.0,
    usage_limit: 100,
    usage_count: 14,
    valid_from: '2026-01-01T00:00:00Z',
    valid_until: '2026-12-31T23:59:59Z',
    active: true,
  },
  {
    id: 'coup-2',
    code: 'BOMDIA15',
    description: 'R$ 15 OFF para pedidos acima de R$ 90',
    discount_type: 'FIXED',
    discount_value: 15.0,
    min_order_value: 90.0,
    usage_limit: 50,
    usage_count: 8,
    valid_from: '2026-01-01T00:00:00Z',
    valid_until: '2026-12-31T23:59:59Z',
    active: true,
  },
];

export const INITIAL_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'zone-1',
    name: 'Centro & Região Imediata',
    neighborhood: 'Centro, Vila Operária',
    fee: 5.0,
    estimated_minutes: 25,
    active: true,
  },
  {
    id: 'zone-2',
    name: 'Bairros Próximos',
    neighborhood: 'Santa Cecília, Bela Vista',
    fee: 8.0,
    estimated_minutes: 35,
    active: true,
  },
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  id: 'store-affeto-main',
  name: 'Affeto Pães Artesanais',
  slug: 'affeto-paes-artesanais',
  description: 'Padaria artesanal de fermentação lenta com levain de 36 horas, ingredientes nobres e respeito ao tempo do trigo.',
  address: 'Rua das Flores, 120 - Centro',
  city: 'Espera Feliz',
  state: 'MG',
  pickup_address: 'Rua das Flores, 120 - Centro, Espera Feliz - MG',
  logo_url: '',
  phone: '(32) 98468-0513',
  whatsapp: '5532984680513',
  pix_key: '32984680513',
  instagram: '@affetopaes',
  is_open: true,
  min_order_value: 20.0,
  free_shipping_threshold: 120.0,
  lead_time_minutes: 45,
  fresh_batch_hours: 'Fornadas frescas diárias saindo às 08h00 e às 15h00.',
  opening_hours: [
    { day: 'Segunda-feira', open: '07:30', close: '19:30', is_closed: false },
    { day: 'Terça-feira', open: '07:30', close: '19:30', is_closed: false },
    { day: 'Quarta-feira', open: '07:30', close: '19:30', is_closed: false },
    { day: 'Quinta-feira', open: '07:30', close: '19:30', is_closed: false },
    { day: 'Sexta-feira', open: '07:30', close: '19:30', is_closed: false },
    { day: 'Sábado', open: '08:00', close: '18:00', is_closed: false },
    { day: 'Domingo', open: '08:00', close: '13:00', is_closed: false },
  ],
};

export const SAMPLE_ORDERS: Order[] = [];
export const INITIAL_PRODUCTION_BATCHES: ProductionBatch[] = [];
